/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

/**
 * Parameters for AudioMedia::startTransmit2() method.
 */
public class AudioMediaTransmitParam {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AudioMediaTransmitParam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AudioMediaTransmitParam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_AudioMediaTransmitParam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Signal level adjustment. Value 1.0 means no level adjustment,<br>
   * while value 0 means to mute the port.<br>
   * <br>
   * Default: 1.0
   */
  public void setLevel(float value) {
    pjsua2JNI.AudioMediaTransmitParam_level_set(swigCPtr, this, value);
  }

  /**
   * Signal level adjustment. Value 1.0 means no level adjustment,<br>
   * while value 0 means to mute the port.<br>
   * <br>
   * Default: 1.0
   */
  public float getLevel() {
    return pjsua2JNI.AudioMediaTransmitParam_level_get(swigCPtr, this);
  }

  /**
   * Default constructor
   */
  public AudioMediaTransmitParam() {
    this(pjsua2JNI.new_AudioMediaTransmitParam(), true);
  }

}
