/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

/**
 * Argument to Endpoint::onNatDetectionComplete() callback.
 */
public class OnNatDetectionCompleteParam {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OnNatDetectionCompleteParam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OnNatDetectionCompleteParam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_OnNatDetectionCompleteParam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Status of the detection process. If this value is not PJ_SUCCESS,<br>
   * the detection has failed and <i>nat_type</i> field will contain<br>
   * PJ_STUN_NAT_TYPE_UNKNOWN.
   */
  public void setStatus(int value) {
    pjsua2JNI.OnNatDetectionCompleteParam_status_set(swigCPtr, this, value);
  }

  /**
   * Status of the detection process. If this value is not PJ_SUCCESS,<br>
   * the detection has failed and <i>nat_type</i> field will contain<br>
   * PJ_STUN_NAT_TYPE_UNKNOWN.
   */
  public int getStatus() {
    return pjsua2JNI.OnNatDetectionCompleteParam_status_get(swigCPtr, this);
  }

  /**
   * The text describing the status, if the status is not PJ_SUCCESS.
   */
  public void setReason(String value) {
    pjsua2JNI.OnNatDetectionCompleteParam_reason_set(swigCPtr, this, value);
  }

  /**
   * The text describing the status, if the status is not PJ_SUCCESS.
   */
  public String getReason() {
    return pjsua2JNI.OnNatDetectionCompleteParam_reason_get(swigCPtr, this);
  }

  /**
   * This contains the NAT type as detected by the detection procedure.<br>
   * This value is only valid when the <i>status</i> is PJ_SUCCESS.
   */
  public void setNatType(int value) {
    pjsua2JNI.OnNatDetectionCompleteParam_natType_set(swigCPtr, this, value);
  }

  /**
   * This contains the NAT type as detected by the detection procedure.<br>
   * This value is only valid when the <i>status</i> is PJ_SUCCESS.
   */
  public int getNatType() {
    return pjsua2JNI.OnNatDetectionCompleteParam_natType_get(swigCPtr, this);
  }

  /**
   * Text describing that NAT type.
   */
  public void setNatTypeName(String value) {
    pjsua2JNI.OnNatDetectionCompleteParam_natTypeName_set(swigCPtr, this, value);
  }

  /**
   * Text describing that NAT type.
   */
  public String getNatTypeName() {
    return pjsua2JNI.OnNatDetectionCompleteParam_natTypeName_get(swigCPtr, this);
  }

  public OnNatDetectionCompleteParam() {
    this(pjsua2JNI.new_OnNatDetectionCompleteParam(), true);
  }

}
