/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

/**
 * This structure contains parameters for Account::sendRequest()
 */
public class SendRequestParam {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SendRequestParam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SendRequestParam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_SendRequestParam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Token or arbitrary user data ownd by the application,<br>
   * which will be passed back in callback Account::onSendRequest().
   */
  public void setUserData(SWIGTYPE_p_void value) {
    pjsua2JNI.SendRequestParam_userData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  /**
   * Token or arbitrary user data ownd by the application,<br>
   * which will be passed back in callback Account::onSendRequest().
   */
  public SWIGTYPE_p_void getUserData() {
    long cPtr = pjsua2JNI.SendRequestParam_userData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  /**
   * SIP method of the request.
   */
  public void setMethod(String value) {
    pjsua2JNI.SendRequestParam_method_set(swigCPtr, this, value);
  }

  /**
   * SIP method of the request.
   */
  public String getMethod() {
    return pjsua2JNI.SendRequestParam_method_get(swigCPtr, this);
  }

  /**
   * Message body and/or list of headers etc. to be included in<br>
   * the outgoing request.
   */
  public void setTxOption(SipTxOption value) {
    pjsua2JNI.SendRequestParam_txOption_set(swigCPtr, this, SipTxOption.getCPtr(value), value);
  }

  /**
   * Message body and/or list of headers etc. to be included in<br>
   * the outgoing request.
   */
  public SipTxOption getTxOption() {
    long cPtr = pjsua2JNI.SendRequestParam_txOption_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SipTxOption(cPtr, false);
  }

  /**
   * Default constructor initializes with zero/empty values.
   */
  public SendRequestParam() {
    this(pjsua2JNI.new_SendRequestParam(), true);
  }

}
