/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

/**
 * Socket option type.
 */
public class SockOpt {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SockOpt(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SockOpt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_SockOpt(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * The level at which the option is defined.
   */
  public void setLevel(int value) {
    pjsua2JNI.SockOpt_level_set(swigCPtr, this, value);
  }

  /**
   * The level at which the option is defined.
   */
  public int getLevel() {
    return pjsua2JNI.SockOpt_level_get(swigCPtr, this);
  }

  /**
   * Option name.
   */
  public void setOptName(int value) {
    pjsua2JNI.SockOpt_optName_set(swigCPtr, this, value);
  }

  /**
   * Option name.
   */
  public int getOptName() {
    return pjsua2JNI.SockOpt_optName_get(swigCPtr, this);
  }

  /**
   *  Default constructor. 
   */
  public SockOpt() {
    this(pjsua2JNI.new_SockOpt__SWIG_0(), true);
  }

  /**
   *  Construct a socket option with the specified parameters. 
   */
  public SockOpt(int level, int optName, int optVal) {
    this(pjsua2JNI.new_SockOpt__SWIG_1(level, optName, optVal), true);
  }

  /**
   * Set option value of type integer.<br>
   * <br>
   * @param opt_val           Option value.
   */
  public void setOptValInt(int opt_val) {
    pjsua2JNI.SockOpt_setOptValInt(swigCPtr, this, opt_val);
  }

}
