/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

/**
 * SSL certificate type and name structure.
 */
public class SslCertName {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SslCertName(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SslCertName obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_SslCertName(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   *  Name type              
   */
  public void setType(int value) {
    pjsua2JNI.SslCertName_type_set(swigCPtr, this, value);
  }

  /**
   *  Name type              
   */
  public int getType() {
    return pjsua2JNI.SslCertName_type_get(swigCPtr, this);
  }

  /**
   *  The name               
   */
  public void setName(String value) {
    pjsua2JNI.SslCertName_name_set(swigCPtr, this, value);
  }

  /**
   *  The name               
   */
  public String getName() {
    return pjsua2JNI.SslCertName_name_get(swigCPtr, this);
  }

  /**
   * Default constructor
   */
  public SslCertName() {
    this(pjsua2JNI.new_SslCertName(), true);
  }

}
